### ISSUE TITLE
Testing Fails

### ISSUE THREAD

**Issue by 2020testuser** [apache/camel-k-examples#33]
Hi, 
Could anyone please help me?
I'm trying to test the Salesforce example.

The Camelsource is not ready and I don't see any errors.

Could anyone please clarify the below?

1. Do I need to deploy the salesforce-source.yaml in namespace-camel-source? Can I  deploy in my own namespace (say, testns) ?
2. When I apply the salesforce-source.yaml, i don't see the status as ready. Is there a way to troubleshoot this issue?
3. The uri: salesforce:camelTestTopic is used in the source.yaml. Do i need to do anything  in salesforce to set this uri? How does camelsource picks this uri?
Thanks in advance

**Comment by oscerd** [comment]
I think you had some response in the main repository.
